<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends Admin_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rating_model');
        $this->load->model('Rating_category_model');
        $this->load->model('Staff_model');
        $this->load->model('Branch_model');
        $this->load->model('User_model');
    }

    function index()
    {
        $this->load->library('form_validation');

        // $this->form_validation->set_rules('password','Password','required|alpha_numeric|min_length[5]');
        $this->form_validation->set_rules('branch', 'Branch', 'required');
        // $this->form_validation->set_rules('staff', 'Staff', 'required');
        $this->form_validation->set_rules('date_from', 'Date From', 'required');
        $this->form_validation->set_rules('date_to', 'Date To', 'required');

        if ($this->form_validation->run()) {
            $branch_id = $this->input->post('branch');
            $staff = $this->input->post('staff');
            $date_from = $this->input->post('date_from');
            $date_to = $this->input->post('date_to');
            
            
            $data['staff']=$this->User_model->get_all_users();
            $data['branch'] = $this->Branch_model->get_all_branch();
            // $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
            $data['ratings'] = $this->Rating_model->get_all_ratings_report($branch_id,$staff,$date_from,$date_to);
            $data['branch_id'] = $branch_id;
            $data['date_from'] = $date_from;
            $data['date_to'] = $date_to;
            $data['staff_id'] = $staff;
            // print_r($staff);
            // exit;
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main', $data);
        }else{
            $data['staff']=$this->User_model->get_all_users();
            $data['branch'] = $this->Branch_model->get_all_branch();
            // $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
            $data['ratings'] = $this->Rating_model->get_all_ratings();
            $data['branch_id'] = 0;
            $data['staff_id'] = array();
            $data['date_from'] = '';
            $data['date_to'] = '';
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main', $data);
        }

       
    }
    function report()
    {
        $this->load->library('form_validation');

        // $this->form_validation->set_rules('password','Password','required|alpha_numeric|min_length[5]');
        $this->form_validation->set_rules('branch', 'Branch', 'required');
        // $this->form_validation->set_rules('staff', 'Staff', 'required');
        $this->form_validation->set_rules('date_from', 'Date From', 'required');
        $this->form_validation->set_rules('date_to', 'Date To', 'required');

        if ($this->form_validation->run()) {
            $branch_id = $this->input->post('branch');
            $staff = $this->input->post('staff');
            $date_from = $this->input->post('date_from');
            $date_to = $this->input->post('date_to');
            
            
            $data['staff'] = $this->Staff_model->get_staffbyBranch($branch_id);
            $data['branch'] = $this->Branch_model->get_all_branch();
            // $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
            $data['ratings'] = $this->Rating_model->get_all_ratings_report($branch_id,$staff,$date_from,$date_to);
            $data['branch_id'] = $branch_id;
            $data['date_from'] = $date_from;
            $data['date_to'] = $date_to;
            $data['staff_id'] = $staff;
            // print_r($staff);
            // exit;
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main', $data);
        } else {
            $data['staff']=$this->User_model->get_all_users();
            $data['branch'] = $this->Branch_model->get_all_branch();
            $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
            $data['ratings'] = $this->Rating_model->get_all_ratings();
            $data['branch_id'] = 0;
            $data['staff_id'] = array();
            $data['date_from'] = '';
            $data['date_to'] = '';
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main', $data);
        }
    }
    // function rc($rcid)
    // {
    //     $data['staff']=$this->Staff_model->get_all_staff();
    // 	$data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
    //     $data['ratings'] = $this->Rating_model->get_all_ratings_rc($rcid);
    //     $data['rc_id']=$rcid;
    //     $data['staff_id']=0;
    //     $data['period']=0;
    //     $data['_view'] = 'dashboard';
    //     $this->load->view('layouts/main',$data);
    // }
    // function staff($staff)
    // {
    //     $data['staff']=$this->Staff_model->get_all_staff();
    // 	$data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
    //     $data['ratings'] = $this->Rating_model->get_all_ratings_staff($staff);
    //     $data['rc_id']=0;
    //     $data['staff_id']=$staff;
    //     $data['period']=0;
    //     $data['_view'] = 'dashboard';
    //     $this->load->view('layouts/main',$data);
    // }
    // function period($period)
    // {
    //     $data['staff']=$this->Staff_model->get_all_staff();
    // 	$data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();
    //     $data['ratings'] = $this->Rating_model->get_all_ratings_period($period);
    //     $data['rc_id']=0;
    //     $data['staff_id']=0;
    //     $data['period']=$period;
    //     $data['_view'] = 'dashboard';
    //     $this->load->view('layouts/main',$data);
    // }

}
