<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Login extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Account_model');

		/*LOAD THE LANGUAGE HELPER */
		$this->lang->load('menu','english');

		if(isset($_SESSION['lang_login'])){
			if($_SESSION['lang_login'] == "en"){
				$this->lang->load('menu','english');
			}
			if($_SESSION['lang_login'] == "ar"){
				$this->lang->load('menu','arabic');
			}
		}
	}

	/*
	 * Listing of tbl_form
	 */
	function index()
	{
		if ($this->session->userdata("email")) {
			redirect('dashboard');
		} else {
			$this->load->view('login/index');
		}
	}

	public function  authenticate(){
		$this->load->library('form_validation');

		$this->form_validation->set_rules('password','password','required');
		$this->form_validation->set_rules('email','email','required');

		$params = array(
			'password' => md5($this->input->post('password')),
			'email' => $this->input->post('email')
		);
		if($this->form_validation->run()){
			$this->load->model('Account_model');
			$data = $this->Account_model->login($params);
			if($data){
				if($data['is_active'] ==1){
					$this->session->set_userdata($data);
					$_SESSION['lang'] = $this->input->post('langauge_selector');
					redirect('dashboard');
				}
				else{
					$this->session->set_flashdata('error', 'Your account is deactivated. Please contact administrator');
					redirect('login', 'refresh');
				}

			}else{
				$this->session->set_flashdata('error', 'Email / Password combinaion does not exist.');
				redirect('login', 'refresh');
			}
		}
	}

	function lang_translator($id){

		if($id == "en"){
			// $this->lang->load('menu','english');
			$_SESSION['lang_login'] = "en";
		}
		
		if($id == "ar"){
			//$this->lang->load('menu','arabic');
			$_SESSION['lang_login'] = "ar";
		}

		redirect('login');
	}

	function  change_password($id)
    {
        $this->load->library('form_validation');
        $data['staff'] = $this->db->query("SELECT * FROM staff s WHERE s.id = {$id}")->row_array();

        if (isset($data['staff']['id'])) {
            $this->form_validation->set_rules('password', 'Password', 'required');

            if ($this->form_validation->run()) {
                $pass = md5($this->input->post('password'));

                $sql = "Update staff SET password = '{$pass}' WHERE id={$data['staff']['id']}";
                $this->db->query($sql);

                redirect('dashboard');
            } else {
                $data['_view'] = 'login/change_password';
                $this->load->view('layouts/main', $data);
            }
        }
    }

	public  function logout()
	{
		$this->session->sess_destroy();
		redirect('login');
	}
    function reset_page(){
        $this->load->view('account/reset_page');
	}
}
