<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Rating extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rating_model');
        $this->load->model('Staff_model');
        $this->load->model('User_model');
        $this->lang->load('menu','arabic');
    }

    /*
     * Listing of ratings
     */
    function index()
    {
        $data['ratings'] = $this->Rating_model->get_all_ratings();
        $data['_view'] = 'rating/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new rating
     */

     function success(){
        $this->load->view('rating/success');
     }

    function form_step_two(){
        
        if(isset($_SESSION['step_one'])){
            $data['form_one'] = $_SESSION['step_one'];
            $this->load->view('rating/next', $data);
        }else{
            redirect('rating/add/'.$_SESSION['user_id']);
        }
        
    }

    function submit_rating(){
        //Get the session values 
        $previous_form =  $_SESSION['step_one'];
        
        $data['staff1'] = $this->User_model->get_user($previous_form['user_id']);

        if($previous_form['rating_type'] == 3){
            $this->load->library('form_validation');
            $this->form_validation->set_rules('reason', 'Reason', 'required');
            if (!$this->form_validation->run()) {
                redirect('rating/form_step_two');
            }
        }

        $params = array(
            'rating_type' => $previous_form['rating_type'],
            'user_id' => $previous_form['user_id'],
            'mobile_no' => $this->input->post('mobile_no'),
            'reason' => $this->input->post('reason'),
        );
        $this->Rating_model->add_rating($params);
        $userinfo=$this->User_model->get_user($previous_form['user_id']);
        $_SESSION['userrname']=$userinfo['first_name'].' '.$userinfo['last_name'];
        redirect('rating/success');
    }

    function add($staff_id)
    {
        $_SESSION['user_id'] = $staff_id;
        $data['staff1'] = $this->User_model->get_user($staff_id);
        
        if (isset($data['staff1']['id'])) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('rating_type', 'Rating Type', 'required');
            if ($this->form_validation->run()) {

                $params = array(
                    'rating_type' => $this->input->post('rating_type'),
                    'user_id' => $staff_id,
                );

                if($params['rating_type'] == 2 || $params['rating_type'] == 1 ){

                    $params = array(
                        'rating_type' =>$this->input->post('rating_type'),
                        'user_id' => $staff_id,
                    );
                    $this->Rating_model->add_rating($params);
                    $userinfo=$this->User_model->get_user($staff_id);
                    $_SESSION['userrname']=$userinfo['first_name'].' '.$userinfo['last_name'];
                    redirect('rating/success');
                }
                

                // Step 1
                $_SESSION['step_one'] = $params;

                redirect('rating/form_step_two');

            } else {
                $data['staff_id'] = $staff_id;
                $this->load->model('Rating_category_model');
                // $data['staff'] = $this->Staff_model->get_all_staff();
                $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();

                // $data['_view'] = 'rating/add';
                $this->load->view('rating/add', $data);
            }
        }
    }

    /*
     * Editing a rating
     */
    function edit($id)
    {
        // check if the rating exists before trying to edit it
        $data['rating'] = $this->Rating_model->get_rating($id);

        if (isset($data['rating']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('staff', 'Staff', 'required');
            $this->form_validation->set_rules('rating_type', 'Rating Type', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'rating_type' => $this->input->post('rating_type'),
                    'user_id' => $this->input->post('staff'),
                    // 'added_by' => $this->input->post('user'),
                    'reason' => $this->input->post('reason'),
                );

                $this->Rating_model->update_rating($id, $params);
                redirect('rating/index');
            } else {
                $this->load->model('Rating_category_model');
                $data['staff'] = $this->Staff_model->get_all_staff();
                $data['all_rating_category'] = $this->Rating_category_model->get_all_rating_category();

                $data['_view'] = 'rating/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The rating you are trying to edit does not exist.');
    }

    /*
     * Deleting rating
     */
    function remove($id)
    {
        $rating = $this->Rating_model->get_rating($id);

        // check if the rating exists before trying to delete it
        if (isset($rating['id'])) {
            $this->Rating_model->delete_rating($id);
            redirect('rating/index');
        } else
            show_error('The rating you are trying to delete does not exist.');
    }
   
}