<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rating_category extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rating_category_model');
    } 

    /*
     * Listing of rating_category
     */
    function index()
    {
        $data['rating_category'] = $this->Rating_category_model->get_all_rating_category();
        
        $data['_view'] = 'rating_category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rating_category
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $rating_category_id = $this->Rating_category_model->add_rating_category($params);
            redirect('rating_category/index');
        }
        else
        {            
            $data['_view'] = 'rating_category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rating_category
     */
    function edit($id)
    {   
        // check if the rating_category exists before trying to edit it
        $data['rating_category'] = $this->Rating_category_model->get_rating_category($id);
        
        if(isset($data['rating_category']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Rating_category_model->update_rating_category($id,$params);            
                redirect('rating_category/index');
            }
            else
            {
                $data['_view'] = 'rating_category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rating_category you are trying to edit does not exist.');
    } 

    /*
     * Deleting rating_category
     */
    function remove($id)
    {
        $rating_category = $this->Rating_category_model->get_rating_category($id);

        // check if the rating_category exists before trying to delete it
        if(isset($rating_category['id']))
        {
            $this->Rating_category_model->delete_rating_category($id);
            redirect('rating_category/index');
        }
        else
            show_error('The rating_category you are trying to delete does not exist.');
    }
    
}
