<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('first_name','First Name','required');
		$this->form_validation->set_rules('last_name','Last Name','required');
		$this->form_validation->set_rules('branch_id','Branch Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'branch_id' => $this->input->post('branch_id'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'mobile_number' => $this->input->post('mobile_number'),
				'city' => $this->input->post('city'),
				'vehicle_type' => $this->input->post('vehicle_type'),
				'model' => $this->input->post('model'),
				'created_by' => $this->session->userdata('id'),
				// 'date_created' => $this->input->post('date_created'),
				// 'rating_id' => $this->input->post('rating_id'),
                // 'user_link' => $this->input->post('user_link'),
                'is_active' => 1
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
			$this->load->model('Branch_model');
			$data['all_branch'] = $this->Branch_model->get_all_branch();
            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($id)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id);
        
        if(isset($data['user']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('first_name','First Name','required');
			$this->form_validation->set_rules('last_name','Last Name','required');
			$this->form_validation->set_rules('branch_id','Branch Id','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'branch_id' => $this->input->post('branch_id'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'mobile_number' => $this->input->post('mobile_number'),
					'city' => $this->input->post('city'),
					'vehicle_type' => $this->input->post('vehicle_type'),
					'model' => $this->input->post('model'),
					'created_by' => $this->session->userdata('id'),
					// 'date_created' => $this->input->post('date_created'),
					// 'rating_id' => $this->input->post('rating_id'),
                    // 'user_link' => $this->input->post('user_link'),
                    'is_active' => $this->input->post('is_active'),
                );

                $this->User_model->update_user($id,$params);            
                redirect('user/index');
            }
            else
            {
				$this->load->model('Branch_model');
				$data['all_branch'] = $this->Branch_model->get_all_branch();

                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id)
    {
        $user = $this->User_model->get_user($id);

        // check if the user exists before trying to delete it
        if(isset($user['id']))
        {
            $this->User_model->delete_user($id);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
