<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Account_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}

	function signup($arr){
	    $if_exist = $this->db->query("SELECT * FROM users WHERE email ='{$arr['email']}'")->row_array();
        if(!isset($if_exist)){
            $this->db->insert('staff', $arr);
        }
    }

	function get_user_byId($id)
	{
		return $this->db->get_where('staff', array('id' => $id))->row_array();
	}
	
	function login($params)
	{
		return $this->db->get_where('staff', $params)->row_array();
	}

	function get_catagories(){
		return $this->db->query("SELECT * from catagory")->result_array();
	}
	function get_subCatagory(){
		return $this->db->query("SELECT * FROM subcatagory")->result_array();
	}
	function get_subCatagory_by_id($id){
		return $this->db->query("SELECT * FROM subcatagory where parent_id ={$id}")->result_array();
	}
}
