<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rating_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rating_category by id
     */
    function get_rating_category($id)
    {
        return $this->db->get_where('rating_category',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all rating_category
     */
    function get_all_rating_category()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('rating_category')->result_array();
    }
        
    /*
     * function to add new rating_category
     */
    function add_rating_category($params)
    {
        $this->db->insert('rating_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rating_category
     */
    function update_rating_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('rating_category',$params);
    }
    
    /*
     * function to delete rating_category
     */
    function delete_rating_category($id)
    {
        return $this->db->delete('rating_category',array('id'=>$id));
    }
}
