<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id
     */
    function get_user($id)
    {
        return $this->db->get_where('users',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $sql ="SELECT u.id, b.branch_name as branch, u.first_name, u.last_name, u.mobile_number, u.city, u.vehicle_type, u.model, u.mobile_number, CASE WHEN u.is_active = 1 THEN 'YES' ELSE 'NO' END as is_active from users u INNER join branch b on u.branch_id = b.id ORDER BY u.id DESC";
        // $this->db->order_by('id', 'desc');
        return $this->db->query($sql)->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        return $this->db->delete('users',array('id'=>$id));
    }
}
